sudo: false
language: java
jdk: oraclejdk7
cache:
  directories: $HOME/.m2
script:
 - if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then mvn deploy --settings settings.xml; else mvn test; fi
